@startuml Casos_de_Uso_Nivel_0
left to right direction

skinparam actorStyle awesome
skinparam packageStyle rectangle
skinparam usecase {
  BackgroundColor #D6E4F0
  BorderColor #2E75B6
  FontColor #1F4E79
  FontSize 12
}
skinparam actor {
  BackgroundColor #EAF4FB
  BorderColor #2E75B6
  FontColor #1F4E79
}
skinparam ArrowColor #2E75B6

' Actores
actor "Productor\nAgrícola" as Productor
actor Operario
actor "Técnico\nAgrónomo" as Tecnico
actor Administrador as Admin

' Sistema
rectangle "Sistema de Gestión Agrícola" {

    ' Gestión (arriba)
    usecase "Gestionar Usuarios" as UC01
    usecase "Administrar Perfil" as UC08

    ' Núcleo productivo (centro)
    usecase "Gestionar Parcelas" as UC02
    usecase "Gestionar Cultivos" as UC03
    usecase "Gestionar Actividades\nAgrícolas" as UC04

    ' Soporte y análisis (abajo)
    usecase "Consultar Información\nClimática" as UC05
    usecase "Gestionar Alertas\ny Recomendaciones" as UC06
    usecase "Gestionar Reportes" as UC07
    usecase "Gestionar Fincas" as UC09
}

' Relaciones Productor
Productor --> UC02
Productor --> UC03
Productor --> UC04
Productor --> UC05
Productor --> UC06
Productor --> UC07
Productor --> UC08
Productor --> UC09

' Relaciones Operario
Operario --> UC04
Operario --> UC08
Operario --> UC03
' Relaciones Técnico
UC02 <-- Tecnico
UC03 <-- Tecnico
UC04 <-- Tecnico
UC05 <-- Tecnico
UC06 <-- Tecnico
UC07 <-- Tecnico
UC08 <-- Tecnico

' Relaciones Admin
UC01 <-- Admin
UC08 <-- Admin

@enduml